from typing import Protocol

from app.domain.models import TodoList, TodoListID


class TodoListRepository(Protocol):
    def all_lists(self) -> list[TodoList]: ...

    def list_by_id(self, id: TodoListID) -> TodoList: ...

    def new_list(self, name: str) -> TodoListID: ...

    def update_list(self, id: TodoListID, name: str) -> None: ...

    def delete_list(self, id: TodoListID) -> None: ...
